Import syft as a library (#2)

diff --git a/.github/workflows/validations.yaml b/.github/workflows/validations.yaml
--- a/.github/workflows/validations.yaml
+++ b/.github/workflows/validations.yaml
@@ -2,6 +2,8 @@ name: "Validations"
 on:
   workflow_dispatch:
   push:
+    branches:
+      - main
   pull_request:
 
 env:
@@ -42,6 +44,15 @@ jobs:
 
       - name: Run static analysis
         run: make static-analysis
+
+      # allow for PRs to skip validating the syft version to allow for incremental updates of syft before release.
+      # In this way checks against the main branch (which are required for release) will fail, but PR checks will not
+      - name: Ensure syft version is a release version
+        run: |
+          echo "GitHub reference: ${GITHUB_REF##*/}"
+          git fetch origin main
+          git merge-base --is-ancestor ${GITHUB_REF##*/} origin/main && make validate-syft-release-version || echo "skipping syft version check"
+
 
   Unit-Test:
     # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
@@ -174,5 +185,60 @@ jobs:
           brew install docker
           mkdir ~/.docker
 
-      - name: Run install.sh tests (Mac)
-        run: make install-test-ci-mac
+# TODO: put back in after the first release
+#      - name: Run install.sh tests (Mac)
+#        run: make install-test-ci-mac
+
+  Cli-Linux:
+    # Note: changing this job name requires making the same update in the .github/workflows/release.yaml pipeline
+    name: "CLI tests (Linux)"
+    needs: [Build-Snapshot-Artifacts]
+    runs-on: ubuntu-20.04
+    steps:
+      - uses: actions/setup-go@v2
+        with:
+          go-version: ${{ env.GO_VERSION }}
+
+      - uses: actions/checkout@v2
+        with:
+          # this downloads and initializes LFS, but does not pull the objects
+          lfs: true
+          # we need to jump between multiple branches to compare compute a diff, which means we need a deeper clone depth
+          fetch-depth: 0
+
+      - name: Restore go cache
+        id: go-cache
+        uses: actions/cache@v2.1.3
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-${{ env.GO_VERSION }}-
+
+      - name: Restore tool cache
+        id: tool-cache
+        uses: actions/cache@v2.1.3
+        with:
+          path: ${{ github.workspace }}/.tmp
+          key: ${{ runner.os }}-tool-${{ hashFiles('Makefile') }}
+
+      - name: (cache-miss) Bootstrap all project dependencies
+        if: steps.tool-cache.outputs.cache-hit != 'true' || steps.go-cache.outputs.cache-hit != 'true'
+        run: make bootstrap
+
+      - name: Build key for tar cache
+        run: make cli-fingerprint
+
+      - name: Restore CLI test cache
+        uses: actions/cache@v2.1.3
+        with:
+          path: ${{ github.workspace }}/test/cli/test-fixtures/cache
+          key: ${{ runner.os }}-cli-test-cache-${{ hashFiles('test/cli/test-fixtures/cache.fingerprint') }}
+
+      - uses: actions/download-artifact@v2
+        with:
+          name: artifacts
+          path: snapshot
+
+      - name: Run CLI Tests (Linux)
+        run: make cli
